import {
  TerrainChunkTemplate,
} from './types/terrainTemplateTypes'

export type {
  TerrainArchetype,
  TerrainBiome,
  TerrainChunkTemplate,
  TerrainTemplatePlatformLayout,
} from './types/terrainTemplateTypes'

export const OPENING_TERRAIN_CHUNK_TEMPLATES: readonly TerrainChunkTemplate[] =
  [
    {
      id: 'graveyard-opening-ridge',
      biome: 'graveyard',
      archetype: 'flat',
      weight: 0,
      minChunk: 0,
      explicitExitRow: 8,
      explicitPlatforms: [
        { localTileX: 0, topRow: 4, widthTiles: 5, role: 'main' },
        { localTileX: 0, topRow: 6, widthTiles: 9, role: 'main' },
        { localTileX: 7, topRow: 8, widthTiles: 9, role: 'main' },
      ],
    },
    {
      id: 'graveyard-opening-basin',
      biome: 'graveyard',
      archetype: 'flat',
      weight: 0,
      minChunk: 0,
      explicitExitRow: 7,
      explicitPlatforms: [
        { localTileX: 0, topRow: 7, widthTiles: 5, role: 'main' },
        { localTileX: 5, topRow: 9, widthTiles: 4, role: 'main' },
        { localTileX: 9, topRow: 8, widthTiles: 7, role: 'main' },
      ],
    },
    {
      id: 'graveyard-opening-recovery',
      biome: 'graveyard',
      archetype: 'recovery',
      weight: 0,
      minChunk: 0,
      explicitExitRow: 6,
      explicitPlatforms: [
        { localTileX: 0, topRow: 8, widthTiles: 6, role: 'main' },
        { localTileX: 5, topRow: 7, widthTiles: 5, role: 'main' },
        { localTileX: 9, topRow: 6, widthTiles: 7, role: 'main' },
      ],
    },
  ]

export const TERRAIN_CHUNK_TEMPLATES: readonly TerrainChunkTemplate[] = [
  {
    id: 'graveyard-transition',
    biome: 'graveyard',
    archetype: 'flat',
    weight: 18,
    minChunk: 0,
    widthRange: [12, 16],
    gapRange: [0, 1],
    rowDeltaRange: [-1, 1],
    floatingPlatformChance: 0.05,
  },
  {
    id: 'graveyard-flat-run',
    biome: 'graveyard',
    archetype: 'flat',
    weight: 28,
    minChunk: 0,
    widthRange: [9, 14],
    gapRange: [0, 2],
    rowDeltaRange: [0, 0],
    floatingPlatformChance: 0.12,
    floatingWidthRange: [2, 3],
    floatingHeightRange: [2, 3],
  },
  {
    id: 'graveyard-step-up',
    biome: 'graveyard',
    archetype: 'step-up',
    weight: 18,
    minChunk: 2,
    widthRange: [8, 12],
    gapRange: [0, 2],
    rowDeltaRange: [1, 3],
    floatingPlatformChance: 0.12,
    floatingWidthRange: [2, 4],
    floatingHeightRange: [2, 4],
  },
  {
    id: 'graveyard-step-down',
    biome: 'graveyard',
    archetype: 'step-down',
    weight: 18,
    minChunk: 2,
    widthRange: [8, 12],
    gapRange: [1, 3],
    rowDeltaRange: [1, 3],
    floatingPlatformChance: 0.08,
    floatingWidthRange: [2, 3],
    floatingHeightRange: [2, 3],
  },
  {
    id: 'graveyard-gap-run',
    biome: 'graveyard',
    archetype: 'gap',
    weight: 16,
    minChunk: 4,
    widthRange: [7, 11],
    gapRange: [2, 5],
    rowDeltaRange: [0, 0],
  },
  {
    id: 'graveyard-floating-chain',
    biome: 'graveyard',
    archetype: 'floating-chain',
    weight: 12,
    minChunk: 5,
    widthRange: [8, 11],
    gapRange: [1, 3],
    rowDeltaRange: [0, 1],
    floatingPlatformChance: 1,
    floatingWidthRange: [2, 4],
    floatingHeightRange: [2, 4],
  },
  {
    id: 'graveyard-recovery',
    biome: 'graveyard',
    archetype: 'recovery',
    weight: 10,
    minChunk: 4,
    widthRange: [11, 15],
    gapRange: [0, 2],
    rowDeltaRange: [1, 2],
  },
]
